theme: minima
title: Student-Produced Project
email: yuhung@ucsd.edu, yul186@ucsd.edu
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
